using BasicCSharpPart2Homework4;

WriteLine("Basic C# - part 2 - Homework 4.");
WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous two terms. " +
    "\nBy starting with 1 and 2, the first 10 terms will be:" +
    "\r\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..." +
    "\r\nBy considering the terms in the Fibonacci sequence whose values do not exceed 1000, " +
    "find the sum of the even-valued terms.");
WriteLine("--------------------------------------------------------");

WriteLine("The sum of even-valued terms in the Fibonacci sequence up to 1000 is: " + FibonacciSum.SumEvenValuedTermsUpToLimit(1000));
WriteLine("The sum of even-valued terms in the Fibonacci sequence up to 100 is: " + FibonacciSum.SumEvenValuedTermsUpToLimit(100));
WriteLine("The sum of even-valued terms in the Fibonacci sequence up to 10 is: " + FibonacciSum.SumEvenValuedTermsUpToLimit(10));